from home_loans.views.home_loan_views import LoanViewSet, RequestViewSet, QuoteViewSet
from home_loans.views.home_loan_views import PriceRequestViewSet, PriceSMSFRequestViewSet, CookieViewSet
from home_loans.views.home_loan_views import AmountRangeViewSet, LVRRangeViewSet, DiscountViewSet
from home_loans.views.home_loan_views import ApplicableStateViewSet, ApplicablePropertyViewSet, ApplicableReasonViewSet